name: Release GameKeyMaster

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Publish Standalone EXE
      run: dotnet publish GameKeyMaster.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true -o ./publish

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: publish/GameKeyMaster.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}